
//
// JEP106, Standard Manufacturer's Identification Code.
//
#include <Library/DebugLib.h>
#include "JEP106.h"

STATIC CHAR8 * CONST Jep106[(JEP106_MAX_BANK_NUM+1) * JEP106_BANK_MAX_ITEM_NUM] = {
  /* Bank0, 0x01 */ "AMD",
  /* Bank0, 0x02 */ "AMI",
  /* Bank0, 0x03 */ "Fairchild",
  /* Bank0, 0x04 */ "Fujitsu",
  /* Bank0, 0x05 */ "GTE",
  /* Bank0, 0x06 */ "Harris",
  /* Bank0, 0x07 */ "Hitachi",
  /* Bank0, 0x08 */ "Inmos",
  /* Bank0, 0x09 */ "Intel",
  /* Bank0, 0x0a */ "I.T.T.",
  /* Bank0, 0x0b */ "Intersil",
  /* Bank0, 0x0c */ "Monolithic Memories",
  /* Bank0, 0x0d */ "Mostek",
  /* Bank0, 0x0e */ "Freescale (Motorola)",
  /* Bank0, 0x0f */ "National",
  /* Bank0, 0x10 */ "NEC",
  /* Bank0, 0x11 */ "RCA",
  /* Bank0, 0x12 */ "Raytheon",
  /* Bank0, 0x13 */ "Conexant (Rockwell)",
  /* Bank0, 0x14 */ "Seeq",
  /* Bank0, 0x15 */ "NXP (Philips)",
  /* Bank0, 0x16 */ "Synertek",
  /* Bank0, 0x17 */ "Texas Instruments",
  /* Bank0, 0x18 */ "Toshiba",
  /* Bank0, 0x19 */ "Xicor",
  /* Bank0, 0x1a */ "Zilog",
  /* Bank0, 0x1b */ "Eurotechnique",
  /* Bank0, 0x1c */ "Mitsubishi",
  /* Bank0, 0x1d */ "Lucent (AT&T)",
  /* Bank0, 0x1e */ "Exel",
  /* Bank0, 0x1f */ "Atmel",
  /* Bank0, 0x20 */ "STMicroelectronics",
  /* Bank0, 0x21 */ "Lattice Semi.",
  /* Bank0, 0x22 */ "NCR",
  /* Bank0, 0x23 */ "Wafer Scale Integration",
  /* Bank0, 0x24 */ "IBM",
  /* Bank0, 0x25 */ "Tristar",
  /* Bank0, 0x26 */ "Visic",
  /* Bank0, 0x27 */ "Intl. CMOS Technology",
  /* Bank0, 0x28 */ "SSSI",
  /* Bank0, 0x29 */ "MicrochipTechnology",
  /* Bank0, 0x2a */ "Ricoh Ltd.",
  /* Bank0, 0x2b */ "VLSI",
  /* Bank0, 0x2c */ "Micron Technology",
  /* Bank0, 0x2d */ "SK Hynix",
  /* Bank0, 0x2e */ "OKI Semiconductor",
  /* Bank0, 0x2f */ "ACTEL",
  /* Bank0, 0x30 */ "Sharp",
  /* Bank0, 0x31 */ "Catalyst",
  /* Bank0, 0x32 */ "Panasonic",
  /* Bank0, 0x33 */ "IDT",
  /* Bank0, 0x34 */ "Cypress",
  /* Bank0, 0x35 */ "DEC",
  /* Bank0, 0x36 */ "LSI Logic",
  /* Bank0, 0x37 */ "Zarlink (Plessey)",
  /* Bank0, 0x38 */ "UTMC",
  /* Bank0, 0x39 */ "Thinking Machine",
  /* Bank0, 0x3a */ "Thomson CSF",
  /* Bank0, 0x3b */ "Integrated CMOS (Vertex)",
  /* Bank0, 0x3c */ "Honeywell",
  /* Bank0, 0x3d */ "Tektronix",
  /* Bank0, 0x3e */ "Oracle Corporation",
  /* Bank0, 0x3f */ "Silicon Storage Technology",
  /* Bank0, 0x40 */ "ProMos/Mosel Vitelic",
  /* Bank0, 0x41 */ "Infineon (Siemens)",
  /* Bank0, 0x42 */ "Macronix",
  /* Bank0, 0x43 */ "Xerox",
  /* Bank0, 0x44 */ "Plus Logic",
  /* Bank0, 0x45 */ "SanDisk Corporation",
  /* Bank0, 0x46 */ "Elan Circuit Tech.",
  /* Bank0, 0x47 */ "European Silicon Str.",
  /* Bank0, 0x48 */ "Apple Computer",
  /* Bank0, 0x49 */ "Xilinx",
  /* Bank0, 0x4a */ "Compaq",
  /* Bank0, 0x4b */ "Protocol Engines",
  /* Bank0, 0x4c */ "SCI",
  /* Bank0, 0x4d */ "Seiko Instruments",
  /* Bank0, 0x4e */ "Samsung",
  /* Bank0, 0x4f */ "I3 Design System",
  /* Bank0, 0x50 */ "Klic",
  /* Bank0, 0x51 */ "Crosspoint Solutions",
  /* Bank0, 0x52 */ "Alliance Semiconductor",
  /* Bank0, 0x53 */ "Tandem",
  /* Bank0, 0x54 */ "Hewlett-Packard",
  /* Bank0, 0x55 */ "Integrated Silicon Solutions",
  /* Bank0, 0x56 */ "Brooktree",
  /* Bank0, 0x57 */ "New Media",
  /* Bank0, 0x58 */ "MHS Electronic",
  /* Bank0, 0x59 */ "Performance Semi.",
  /* Bank0, 0x5a */ "Winbond Electronic",
  /* Bank0, 0x5b */ "Kawasaki Steel",
  /* Bank0, 0x5c */ "Bright Micro",
  /* Bank0, 0x5d */ "TECMAR",
  /* Bank0, 0x5e */ "Exar",
  /* Bank0, 0x5f */ "PCMCIA",
  /* Bank0, 0x60 */ "LG Semi (Goldstar)",
  /* Bank0, 0x61 */ "Northern Telecom",
  /* Bank0, 0x62 */ "Sanyo",
  /* Bank0, 0x63 */ "Array Microsystems",
  /* Bank0, 0x64 */ "Crystal Semiconductor",
  /* Bank0, 0x65 */ "Analog Devices",
  /* Bank0, 0x66 */ "PMC-Sierra",
  /* Bank0, 0x67 */ "Asparix",
  /* Bank0, 0x68 */ "Convex Computer",
  /* Bank0, 0x69 */ "Quality Semiconductor",
  /* Bank0, 0x6a */ "Nimbus Technology",
  /* Bank0, 0x6b */ "Transwitch",
  /* Bank0, 0x6c */ "Micronas (ITT Intermetall)",
  /* Bank0, 0x6d */ "Cannon",
  /* Bank0, 0x6e */ "Altera",
  /* Bank0, 0x6f */ "NEXCOM",
  /* Bank0, 0x70 */ "Qualcomm",
  /* Bank0, 0x71 */ "Sony",
  /* Bank0, 0x72 */ "Cray Research",
  /* Bank0, 0x73 */ "AMS(Austria Micro)",
  /* Bank0, 0x74 */ "Vitesse",
  /* Bank0, 0x75 */ "Aster Electronics",
  /* Bank0, 0x76 */ "Bay Networks (Synoptic)",
  /* Bank0, 0x77 */ "Zentrum/ZMD",
  /* Bank0, 0x78 */ "TRW",
  /* Bank0, 0x79 */ "Thesys",
  /* Bank0, 0x7a */ "Solbourne Computer",
  /* Bank0, 0x7b */ "Allied-Signal",
  /* Bank0, 0x7c */ "Dialog Semiconductor",
  /* Bank0, 0x7d */ "Media Vision",
  /* Bank0, 0x7e */ "Numonyx Corporation",
  /* Bank1, 0x01 */ "Cirrus Logic",
  /* Bank1, 0x02 */ "National Instruments",
  /* Bank1, 0x03 */ "ILC Data Device",
  /* Bank1, 0x04 */ "Alcatel Mietec",
  /* Bank1, 0x05 */ "Micro Linear",
  /* Bank1, 0x06 */ "Univ. of NC",
  /* Bank1, 0x07 */ "JTAG Technologies",
  /* Bank1, 0x08 */ "BAE Systems (Loral)",
  /* Bank1, 0x09 */ "Nchip",
  /* Bank1, 0x0a */ "Galileo Tech",
  /* Bank1, 0x0b */ "Bestlink Systems",
  /* Bank1, 0x0c */ "Graychip",
  /* Bank1, 0x0d */ "GENNUM",
  /* Bank1, 0x0e */ "VideoLogic",
  /* Bank1, 0x0f */ "Robert Bosch",
  /* Bank1, 0x10 */ "Chip Express",
  /* Bank1, 0x11 */ "DATARAM",
  /* Bank1, 0x12 */ "United Microelectronics Corp.",
  /* Bank1, 0x13 */ "TCSI",
  /* Bank1, 0x14 */ "Smart Modular",
  /* Bank1, 0x15 */ "Hughes Aircraft",
  /* Bank1, 0x16 */ "Lanstar Semiconductor",
  /* Bank1, 0x17 */ "Qlogic",
  /* Bank1, 0x18 */ "Kingston",
  /* Bank1, 0x19 */ "Music Semi",
  /* Bank1, 0x1a */ "Ericsson Components",
  /* Bank1, 0x1b */ "SpaSE",
  /* Bank1, 0x1c */ "Eon Silicon Devices",
  /* Bank1, 0x1d */ "Integrated Silicon Solution (ISSI)",
  /* Bank1, 0x1e */ "DoD",
  /* Bank1, 0x1f */ "Integ. Memories Tech.",
  /* Bank1, 0x20 */ "Corollary Inc.",
  /* Bank1, 0x21 */ "Dallas Semiconductor",
  /* Bank1, 0x22 */ "Omnivision",
  /* Bank1, 0x23 */ "EIV(Switzerland)",
  /* Bank1, 0x24 */ "Novatel Wireless",
  /* Bank1, 0x25 */ "Zarlink (Mitel)",
  /* Bank1, 0x26 */ "Clearpoint",
  /* Bank1, 0x27 */ "Cabletron",
  /* Bank1, 0x28 */ "STEC (Silicon Tech)",
  /* Bank1, 0x29 */ "Vanguard",
  /* Bank1, 0x2a */ "Hagiwara Sys-Com",
  /* Bank1, 0x2b */ "Vantis",
  /* Bank1, 0x2c */ "Celestica",
  /* Bank1, 0x2d */ "Century",
  /* Bank1, 0x2e */ "Hal Computers",
  /* Bank1, 0x2f */ "Rohm Company Ltd.",
  /* Bank1, 0x30 */ "Juniper Networks",
  /* Bank1, 0x31 */ "Libit Signal Processing",
  /* Bank1, 0x32 */ "Mushkin Enhanced Memory",
  /* Bank1, 0x33 */ "Tundra Semiconductor",
  /* Bank1, 0x34 */ "Adaptec Inc.",
  /* Bank1, 0x35 */ "LightSpeed Semi.",
  /* Bank1, 0x36 */ "ZSP Corp.",
  /* Bank1, 0x37 */ "AMIC Technology",
  /* Bank1, 0x38 */ "Adobe Systems",
  /* Bank1, 0x39 */ "Dynachip",
  /* Bank1, 0x3a */ "PNY Technologies, Inc.",
  /* Bank1, 0x3b */ "Newport Digital",
  /* Bank1, 0x3c */ "MMC Networks",
  /* Bank1, 0x3d */ "T Square",
  /* Bank1, 0x3e */ "Seiko Epson",
  /* Bank1, 0x3f */ "Broadcom",
  /* Bank1, 0x40 */ "Viking Components",
  /* Bank1, 0x41 */ "V3 Semiconductor",
  /* Bank1, 0x42 */ "Flextronics (Orbit Semiconductor)",
  /* Bank1, 0x43 */ "Suwa Electronics",
  /* Bank1, 0x44 */ "Transmeta",
  /* Bank1, 0x45 */ "Micron CMS",
  /* Bank1, 0x46 */ "American Computer & Digital",
  /* Bank1, 0x47 */ "Enhance 3000 Inc.",
  /* Bank1, 0x48 */ "Tower Semiconductor",
  /* Bank1, 0x49 */ "CPU Design",
  /* Bank1, 0x4a */ "Price Point",
  /* Bank1, 0x4b */ "Maxim Integrated Product",
  /* Bank1, 0x4c */ "Tellabs",
  /* Bank1, 0x4d */ "Centaur Technology",
  /* Bank1, 0x4e */ "Unigen Corporation",
  /* Bank1, 0x4f */ "Transcend Information",
  /* Bank1, 0x50 */ "Memory Card Technology",
  /* Bank1, 0x51 */ "CKD Corporation Ltd.",
  /* Bank1, 0x52 */ "Capital Instruments, Inc.",
  /* Bank1, 0x53 */ "Aica Kogyo, Ltd.",
  /* Bank1, 0x54 */ "Linvex Technology",
  /* Bank1, 0x55 */ "MSC Vertriebs GmbH",
  /* Bank1, 0x56 */ "AKM Company, Ltd.",
  /* Bank1, 0x57 */ "Dynamem, Inc.",
  /* Bank1, 0x58 */ "NERA ASA",
  /* Bank1, 0x59 */ "GSI Technology",
  /* Bank1, 0x5a */ "Dane-Elec (C Memory)",
  /* Bank1, 0x5b */ "Acorn Computers",
  /* Bank1, 0x5c */ "Lara Technology",
  /* Bank1, 0x5d */ "Oak Technology, Inc.",
  /* Bank1, 0x5e */ "Itec Memory",
  /* Bank1, 0x5f */ "Tanisys Technology",
  /* Bank1, 0x60 */ "Truevision",
  /* Bank1, 0x61 */ "Wintec Industries",
  /* Bank1, 0x62 */ "Super PC Memory",
  /* Bank1, 0x63 */ "MGV Memory",
  /* Bank1, 0x64 */ "Galvantech",
  /* Bank1, 0x65 */ "Gadzoox Networks",
  /* Bank1, 0x66 */ "Multi Dimensional Cons.",
  /* Bank1, 0x67 */ "GateField",
  /* Bank1, 0x68 */ "Integrated Memory System",
  /* Bank1, 0x69 */ "Triscend",
  /* Bank1, 0x6a */ "XaQti",
  /* Bank1, 0x6b */ "Goldenram",
  /* Bank1, 0x6c */ "Clear Logic",
  /* Bank1, 0x6d */ "Cimaron Communications",
  /* Bank1, 0x6e */ "Nippon Steel Semi. Corp.",
  /* Bank1, 0x6f */ "Advantage Memory",
  /* Bank1, 0x70 */ "AMCC",
  /* Bank1, 0x71 */ "LeCroy",
  /* Bank1, 0x72 */ "Yamaha Corporation",
  /* Bank1, 0x73 */ "Digital Microwave",
  /* Bank1, 0x74 */ "NetLogic Microsystems",
  /* Bank1, 0x75 */ "MIMOS Semiconductor",
  /* Bank1, 0x76 */ "Advanced Fibre",
  /* Bank1, 0x77 */ "BF Goodrich Data.",
  /* Bank1, 0x78 */ "Epigram",
  /* Bank1, 0x79 */ "Acbel Polytech Inc.",
  /* Bank1, 0x7a */ "Apacer Technology",
  /* Bank1, 0x7b */ "Admor Memory",
  /* Bank1, 0x7c */ "FOXCONN",
  /* Bank1, 0x7d */ "Quadratics Superconductor",
  /* Bank1, 0x7e */ "3COM",
  /* Bank2, 0x01 */ "Camintonn Corporation",
  /* Bank2, 0x02 */ "ISOA Incorporated",
  /* Bank2, 0x03 */ "Agate Semiconductor",
  /* Bank2, 0x04 */ "ADMtek Incorporated",
  /* Bank2, 0x05 */ "HYPERTEC",
  /* Bank2, 0x06 */ "Adhoc Technologies",
  /* Bank2, 0x07 */ "MOSAID Technologies",
  /* Bank2, 0x08 */ "Ardent Technologies",
  /* Bank2, 0x09 */ "Switchcore",
  /* Bank2, 0x0a */ "Cisco Systems, Inc.",
  /* Bank2, 0x0b */ "Allayer Technologies",
  /* Bank2, 0x0c */ "WorkX AG (Wichman)",
  /* Bank2, 0x0d */ "Oasis Semiconductor",
  /* Bank2, 0x0e */ "Novanet Semiconductor",
  /* Bank2, 0x0f */ "E-M Solutions",
  /* Bank2, 0x10 */ "Power General",
  /* Bank2, 0x11 */ "Advanced Hardware Arch.",
  /* Bank2, 0x12 */ "Inova Semiconductors GmbH",
  /* Bank2, 0x13 */ "Telocity",
  /* Bank2, 0x14 */ "Delkin Devices",
  /* Bank2, 0x15 */ "Symagery Microsystems",
  /* Bank2, 0x16 */ "C-Port Corporation",
  /* Bank2, 0x17 */ "SiberCore Technologies",
  /* Bank2, 0x18 */ "Southland Microsystems",
  /* Bank2, 0x19 */ "Malleable Technologies",
  /* Bank2, 0x1a */ "Kendin Communications",
  /* Bank2, 0x1b */ "Great Technology Microcomputer",
  /* Bank2, 0x1c */ "Sanmina Corporation",
  /* Bank2, 0x1d */ "HADCO Corporation",
  /* Bank2, 0x1e */ "Corsair",
  /* Bank2, 0x1f */ "Actrans System Inc.",
  /* Bank2, 0x20 */ "ALPHA Technologies",
  /* Bank2, 0x21 */ "Silicon Laboratories, Inc. (Cygnal)",
  /* Bank2, 0x22 */ "Artesyn Technologies",
  /* Bank2, 0x23 */ "Align Manufacturing",
  /* Bank2, 0x24 */ "Peregrine Semiconductor",
  /* Bank2, 0x25 */ "Chameleon Systems",
  /* Bank2, 0x26 */ "Aplus Flash Technology",
  /* Bank2, 0x27 */ "MIPS Technologies",
  /* Bank2, 0x28 */ "Chrysalis ITS",
  /* Bank2, 0x29 */ "ADTEC Corporation",
  /* Bank2, 0x2a */ "Kentron Technologies",
  /* Bank2, 0x2b */ "Win Technologies",
  /* Bank2, 0x2c */ "Tezzaron Semiconductor",
  /* Bank2, 0x2d */ "Extreme Packet Devices",
  /* Bank2, 0x2e */ "RF Micro Devices",
  /* Bank2, 0x2f */ "Siemens AG",
  /* Bank2, 0x30 */ "Sarnoff Corporation",
  /* Bank2, 0x31 */ "Itautec SA",
  /* Bank2, 0x32 */ "Radiata Inc.",
  /* Bank2, 0x33 */ "Benchmark Elect. (AVEX)",
  /* Bank2, 0x34 */ "Legend",
  /* Bank2, 0x35 */ "SpecTek Incorporated",
  /* Bank2, 0x36 */ "Hi/fn",
  /* Bank2, 0x37 */ "Enikia Incorporated",
  /* Bank2, 0x38 */ "SwitchOn Networks",
  /* Bank2, 0x39 */ "AANetcom Incorporated",
  /* Bank2, 0x3a */ "Micro Memory Bank",
  /* Bank2, 0x3b */ "ESS Technology",
  /* Bank2, 0x3c */ "Virata Corporation",
  /* Bank2, 0x3d */ "Excess Bandwidth",
  /* Bank2, 0x3e */ "West Bay Semiconductor",
  /* Bank2, 0x3f */ "DSP Group",
  /* Bank2, 0x40 */ "Newport Communications",
  /* Bank2, 0x41 */ "Chip2Chip Incorporated",
  /* Bank2, 0x42 */ "Phobos Corporation",
  /* Bank2, 0x43 */ "Intellitech Corporation",
  /* Bank2, 0x44 */ "Nordic VLSI ASA",
  /* Bank2, 0x45 */ "Ishoni Networks",
  /* Bank2, 0x46 */ "Silicon Spice",
  /* Bank2, 0x47 */ "Alchemy Semiconductor",
  /* Bank2, 0x48 */ "Agilent Technologies",
  /* Bank2, 0x49 */ "Centillium Communications",
  /* Bank2, 0x4a */ "W.L. Gore",
  /* Bank2, 0x4b */ "HanBit Electronics",
  /* Bank2, 0x4c */ "GlobeSpan",
  /* Bank2, 0x4d */ "Element 14",
  /* Bank2, 0x4e */ "Pycon",
  /* Bank2, 0x4f */ "Saifun Semiconductors",
  /* Bank2, 0x50 */ "Sibyte, Incorporated",
  /* Bank2, 0x51 */ "MetaLink Technologies",
  /* Bank2, 0x52 */ "Feiya Technology",
  /* Bank2, 0x53 */ "I & C Technology",
  /* Bank2, 0x54 */ "Shikatronics",
  /* Bank2, 0x55 */ "Elektrobit",
  /* Bank2, 0x56 */ "Megic",
  /* Bank2, 0x57 */ "Com-Tier",
  /* Bank2, 0x58 */ "Malaysia Micro Solutions",
  /* Bank2, 0x59 */ "Hyperchip",
  /* Bank2, 0x5a */ "Gemstone Communications",
  /* Bank2, 0x5b */ "Anadigm (Anadyne)",
  /* Bank2, 0x5c */ "3ParData",
  /* Bank2, 0x5d */ "Mellanox Technologies",
  /* Bank2, 0x5e */ "Tenx Technologies",
  /* Bank2, 0x5f */ "Helix AG",
  /* Bank2, 0x60 */ "Domosys",
  /* Bank2, 0x61 */ "Skyup Technology",
  /* Bank2, 0x62 */ "HiNT Corporation",
  /* Bank2, 0x63 */ "Chiaro",
  /* Bank2, 0x64 */ "MDT Technologies GmbH",
  /* Bank2, 0x65 */ "Exbit Technology A/S",
  /* Bank2, 0x66 */ "Integrated Technology Express",
  /* Bank2, 0x67 */ "AVED Memory",
  /* Bank2, 0x68 */ "Legerity",
  /* Bank2, 0x69 */ "Jasmine Networks",
  /* Bank2, 0x6a */ "Caspian Networks",
  /* Bank2, 0x6b */ "nCUBE",
  /* Bank2, 0x6c */ "Silicon Access Networks",
  /* Bank2, 0x6d */ "FDK Corporation",
  /* Bank2, 0x6e */ "High Bandwidth Access",
  /* Bank2, 0x6f */ "MultiLink Technology",
  /* Bank2, 0x70 */ "BRECIS",
  /* Bank2, 0x71 */ "World Wide Packets",
  /* Bank2, 0x72 */ "APW",
  /* Bank2, 0x73 */ "Chicory Systems",
  /* Bank2, 0x74 */ "Xstream Logic",
  /* Bank2, 0x75 */ "Fast-Chip",
  /* Bank2, 0x76 */ "Zucotto Wireless",
  /* Bank2, 0x77 */ "Realchip",
  /* Bank2, 0x78 */ "Galaxy Power",
  /* Bank2, 0x79 */ "eSilicon",
  /* Bank2, 0x7a */ "Morphics Technology",
  /* Bank2, 0x7b */ "Accelerant Networks",
  /* Bank2, 0x7c */ "Silicon Wave",
  /* Bank2, 0x7d */ "SandCraft",
  /* Bank2, 0x7e */ "Elpida",
  /* Bank3, 0x01 */ "Solectron",
  /* Bank3, 0x02 */ "Optosys Technologies",
  /* Bank3, 0x03 */ "Buffalo (Formerly Melco)",
  /* Bank3, 0x04 */ "TriMedia Technologies",
  /* Bank3, 0x05 */ "Cyan Technologies",
  /* Bank3, 0x06 */ "Global Locate",
  /* Bank3, 0x07 */ "Optillion",
  /* Bank3, 0x08 */ "Terago Communications",
  /* Bank3, 0x09 */ "Ikanos Communications",
  /* Bank3, 0x0a */ "Princeton Technology",
  /* Bank3, 0x0b */ "Nanya Technology",
  /* Bank3, 0x0c */ "Elite Flash Storage",
  /* Bank3, 0x0d */ "Mysticom",
  /* Bank3, 0x0e */ "LightSand Communications",
  /* Bank3, 0x0f */ "ATI Technologies",
  /* Bank3, 0x10 */ "Agere Systems",
  /* Bank3, 0x11 */ "NeoMagic",
  /* Bank3, 0x12 */ "AuroraNetics",
  /* Bank3, 0x13 */ "Golden Empire",
  /* Bank3, 0x14 */ "Mushkin",
  /* Bank3, 0x15 */ "Tioga Technologies",
  /* Bank3, 0x16 */ "Netlist",
  /* Bank3, 0x17 */ "TeraLogic",
  /* Bank3, 0x18 */ "Cicada Semiconductor",
  /* Bank3, 0x19 */ "Centon Electronics",
  /* Bank3, 0x1a */ "Tyco Electronics",
  /* Bank3, 0x1b */ "Magis Works",
  /* Bank3, 0x1c */ "Zettacom",
  /* Bank3, 0x1d */ "Cogency Semiconductor",
  /* Bank3, 0x1e */ "Chipcon AS",
  /* Bank3, 0x1f */ "Aspex Technology",
  /* Bank3, 0x20 */ "F5 Networks",
  /* Bank3, 0x21 */ "Programmable Silicon Solutions",
  /* Bank3, 0x22 */ "ChipWrights",
  /* Bank3, 0x23 */ "Acorn Networks",
  /* Bank3, 0x24 */ "Quicklogic",
  /* Bank3, 0x25 */ "Kingmax Semiconductor",
  /* Bank3, 0x26 */ "BOPS",
  /* Bank3, 0x27 */ "Flasys",
  /* Bank3, 0x28 */ "BitBlitz Communications",
  /* Bank3, 0x29 */ "eMemory Technology",
  /* Bank3, 0x2a */ "Procket Networks",
  /* Bank3, 0x2b */ "Purple Ray",
  /* Bank3, 0x2c */ "Trebia Networks",
  /* Bank3, 0x2d */ "Delta Electronics",
  /* Bank3, 0x2e */ "Onex Communications",
  /* Bank3, 0x2f */ "Ample Communications",
  /* Bank3, 0x30 */ "Memory Experts Intl",
  /* Bank3, 0x31 */ "Astute Networks",
  /* Bank3, 0x32 */ "Azanda Network Devices",
  /* Bank3, 0x33 */ "Dibcom",
  /* Bank3, 0x34 */ "Tekmos",
  /* Bank3, 0x35 */ "API NetWorks",
  /* Bank3, 0x36 */ "Bay Microsystems",
  /* Bank3, 0x37 */ "Firecron Ltd",
  /* Bank3, 0x38 */ "Resonext Communications",
  /* Bank3, 0x39 */ "Tachys Technologies",
  /* Bank3, 0x3a */ "Equator Technology",
  /* Bank3, 0x3b */ "Concept Computer",
  /* Bank3, 0x3c */ "SILCOM",
  /* Bank3, 0x3d */ "3Dlabs",
  /* Bank3, 0x3e */ "ct Magazine",
  /* Bank3, 0x3f */ "Sanera Systems",
  /* Bank3, 0x40 */ "Silicon Packets",
  /* Bank3, 0x41 */ "Viasystems Group",
  /* Bank3, 0x42 */ "Simtek",
  /* Bank3, 0x43 */ "Semicon Devices Singapore",
  /* Bank3, 0x44 */ "Satron Handelsges",
  /* Bank3, 0x45 */ "Improv Systems",
  /* Bank3, 0x46 */ "INDUSYS GmbH",
  /* Bank3, 0x47 */ "Corrent",
  /* Bank3, 0x48 */ "Infrant Technologies",
  /* Bank3, 0x49 */ "Ritek Corp",
  /* Bank3, 0x4a */ "empowerTel Networks",
  /* Bank3, 0x4b */ "Hypertec",
  /* Bank3, 0x4c */ "Cavium Networks",
  /* Bank3, 0x4d */ "PLX Technology",
  /* Bank3, 0x4e */ "Massana Design",
  /* Bank3, 0x4f */ "Intrinsity",
  /* Bank3, 0x50 */ "Valence Semiconductor",
  /* Bank3, 0x51 */ "Terawave Communications",
  /* Bank3, 0x52 */ "IceFyre Semiconductor",
  /* Bank3, 0x53 */ "Primarion",
  /* Bank3, 0x54 */ "Picochip Designs Ltd",
  /* Bank3, 0x55 */ "Silverback Systems",
  /* Bank3, 0x56 */ "Jade Star Technologies",
  /* Bank3, 0x57 */ "Pijnenburg Securealink",
  /* Bank3, 0x58 */ "takeMS - Ultron AG",
  /* Bank3, 0x59 */ "Cambridge Silicon Radio",
  /* Bank3, 0x5a */ "Swissbit",
  /* Bank3, 0x5b */ "Nazomi Communications",
  /* Bank3, 0x5c */ "eWave System",
  /* Bank3, 0x5d */ "Rockwell Collins",
  /* Bank3, 0x5e */ "Picocel Co. Ltd. (Paion)",
  /* Bank3, 0x5f */ "Alphamosaic Ltd",
  /* Bank3, 0x60 */ "Sandburst",
  /* Bank3, 0x61 */ "SiCon Video",
  /* Bank3, 0x62 */ "NanoAmp Solutions",
  /* Bank3, 0x63 */ "Ericsson Technology",
  /* Bank3, 0x64 */ "PrairieComm",
  /* Bank3, 0x65 */ "Mitac International",
  /* Bank3, 0x66 */ "Layer N Networks",
  /* Bank3, 0x67 */ "MtekVision (Atsana)",
  /* Bank3, 0x68 */ "Allegro Networks",
  /* Bank3, 0x69 */ "Marvell Semiconductors",
  /* Bank3, 0x6a */ "Netergy Microelectronic",
  /* Bank3, 0x6b */ "NVIDIA",
  /* Bank3, 0x6c */ "Internet Machines",
  /* Bank3, 0x6d */ "Memorysolution GmbH",
  /* Bank3, 0x6e */ "Litchfield Communication",
  /* Bank3, 0x6f */ "Accton Technology",
  /* Bank3, 0x70 */ "Teradiant Networks",
  /* Bank3, 0x71 */ "Scaleo Chip",
  /* Bank3, 0x72 */ "Cortina Systems",
  /* Bank3, 0x73 */ "RAM Components",
  /* Bank3, 0x74 */ "Raqia Networks",
  /* Bank3, 0x75 */ "ClearSpeed",
  /* Bank3, 0x76 */ "Matsushita Battery",
  /* Bank3, 0x77 */ "Xelerated",
  /* Bank3, 0x78 */ "SimpleTech",
  /* Bank3, 0x79 */ "Utron Technology",
  /* Bank3, 0x7a */ "Astec International",
  /* Bank3, 0x7b */ "AVM gmbH",
  /* Bank3, 0x7c */ "Redux Communications",
  /* Bank3, 0x7d */ "Dot Hill Systems",
  /* Bank3, 0x7e */ "TeraChip",
  /* Bank4, 0x01 */ "T-RAM Incorporated",
  /* Bank4, 0x02 */ "Innovics Wireless",
  /* Bank4, 0x03 */ "Teknovus",
  /* Bank4, 0x04 */ "KeyEye Communications",
  /* Bank4, 0x05 */ "Runcom Technologies",
  /* Bank4, 0x06 */ "RedSwitch",
  /* Bank4, 0x07 */ "Dotcast",
  /* Bank4, 0x08 */ "Silicon Mountain Memory",
  /* Bank4, 0x09 */ "Signia Technologies",
  /* Bank4, 0x0a */ "Pixim",
  /* Bank4, 0x0b */ "Galazar Networks",
  /* Bank4, 0x0c */ "White Electronic Designs",
  /* Bank4, 0x0d */ "Patriot Scientific",
  /* Bank4, 0x0e */ "Neoaxiom Corporation",
  /* Bank4, 0x0f */ "3Y Power Technology",
  /* Bank4, 0x10 */ "Scaleo Chip",
  /* Bank4, 0x11 */ "Potentia Power Systems",
  /* Bank4, 0x12 */ "C-guys Incorporated",
  /* Bank4, 0x13 */ "Digital Communications Technology",
  /* Bank4, 0x14 */ "Silicon-Based Technology",
  /* Bank4, 0x15 */ "Fulcrum Microsystems",
  /* Bank4, 0x16 */ "Positivo Informatica Ltd",
  /* Bank4, 0x17 */ "XIOtech Corporation",
  /* Bank4, 0x18 */ "PortalPlayer",
  /* Bank4, 0x19 */ "Zhiying Software",
  /* Bank4, 0x1a */ "ParkerVision, Inc.",
  /* Bank4, 0x1b */ "Phonex Broadband",
  /* Bank4, 0x1c */ "Skyworks Solutions",
  /* Bank4, 0x1d */ "Entropic Communications",
  /* Bank4, 0x1e */ "IM Intelligent Memory Ltd.",
  /* Bank4, 0x1f */ "Zensys A/S",
  /* Bank4, 0x20 */ "Legend Silicon Corp.",
  /* Bank4, 0x21 */ "Sci-worx GmbH",
  /* Bank4, 0x22 */ "SMSC (Standard Microsystems)",
  /* Bank4, 0x23 */ "Renesas Electronics",
  /* Bank4, 0x24 */ "Raza Microelectronics",
  /* Bank4, 0x25 */ "Phyworks",
  /* Bank4, 0x26 */ "MediaTek",
  /* Bank4, 0x27 */ "Non-cents Productions",
  /* Bank4, 0x28 */ "US Modular",
  /* Bank4, 0x29 */ "Wintegra Ltd.",
  /* Bank4, 0x2a */ "Mathstar",
  /* Bank4, 0x2b */ "StarCore",
  /* Bank4, 0x2c */ "Oplus Technologies",
  /* Bank4, 0x2d */ "Mindspeed",
  /* Bank4, 0x2e */ "Just Young Computer",
  /* Bank4, 0x2f */ "Radia Communications",
  /* Bank4, 0x30 */ "OCZ",
  /* Bank4, 0x31 */ "Emuzed",
  /* Bank4, 0x32 */ "LOGIC Devices",
  /* Bank4, 0x33 */ "Inphi Corporation",
  /* Bank4, 0x34 */ "Quake Technologies",
  /* Bank4, 0x35 */ "Vixel",
  /* Bank4, 0x36 */ "SolusTek",
  /* Bank4, 0x37 */ "Kongsberg Maritime",
  /* Bank4, 0x38 */ "Faraday Technology",
  /* Bank4, 0x39 */ "Altium Ltd.",
  /* Bank4, 0x3a */ "Insyte",
  /* Bank4, 0x3b */ "ARM Ltd.",
  /* Bank4, 0x3c */ "DigiVision",
  /* Bank4, 0x3d */ "Vativ Technologies",
  /* Bank4, 0x3e */ "Endicott Interconnect Technologies",
  /* Bank4, 0x3f */ "Pericom",
  /* Bank4, 0x40 */ "Bandspeed",
  /* Bank4, 0x41 */ "LeWiz Communications",
  /* Bank4, 0x42 */ "CPU Technology",
  /* Bank4, 0x43 */ "Ramaxel Technology",
  /* Bank4, 0x44 */ "DSP Group",
  /* Bank4, 0x45 */ "Axis Communications",
  /* Bank4, 0x46 */ "Legacy Electronics",
  /* Bank4, 0x47 */ "Chrontel",
  /* Bank4, 0x48 */ "Powerchip Semiconductor",
  /* Bank4, 0x49 */ "MobilEye Technologies",
  /* Bank4, 0x4a */ "Excel Semiconductor",
  /* Bank4, 0x4b */ "A-DATA Technology",
  /* Bank4, 0x4c */ "VirtualDigm",
  /* Bank4, 0x4d */ "G Skill Intl",
  /* Bank4, 0x4e */ "Quanta Computer",
  /* Bank4, 0x4f */ "Yield Microelectronics",
  /* Bank4, 0x50 */ "Afa Technologies",
  /* Bank4, 0x51 */ "KINGBOX Technology Co. Ltd.",
  /* Bank4, 0x52 */ "Ceva",
  /* Bank4, 0x53 */ "iStor Networks",
  /* Bank4, 0x54 */ "Advance Modules",
  /* Bank4, 0x55 */ "Microsoft",
  /* Bank4, 0x56 */ "Open-Silicon",
  /* Bank4, 0x57 */ "Goal Semiconductor",
  /* Bank4, 0x58 */ "ARC International",
  /* Bank4, 0x59 */ "Simmtec",
  /* Bank4, 0x5a */ "Metanoia",
  /* Bank4, 0x5b */ "Key Stream",
  /* Bank4, 0x5c */ "Lowrance Electronics",
  /* Bank4, 0x5d */ "Adimos",
  /* Bank4, 0x5e */ "SiGe Semiconductor",
  /* Bank4, 0x5f */ "Fodus Communications",
  /* Bank4, 0x60 */ "Credence Systems Corp.",
  /* Bank4, 0x61 */ "Genesis Microchip Inc.",
  /* Bank4, 0x62 */ "Vihana, Inc.",
  /* Bank4, 0x63 */ "WIS Technologies",
  /* Bank4, 0x64 */ "GateChange Technologies",
  /* Bank4, 0x65 */ "High Density Devices AS",
  /* Bank4, 0x66 */ "Synopsys",
  /* Bank4, 0x67 */ "Gigaram",
  /* Bank4, 0x68 */ "Enigma Semiconductor Inc.",
  /* Bank4, 0x69 */ "Century Micro Inc.",
  /* Bank4, 0x6a */ "Icera Semiconductor",
  /* Bank4, 0x6b */ "Mediaworks Integrated Systems",
  /* Bank4, 0x6c */ "ONeil Product Development",
  /* Bank4, 0x6d */ "Supreme Top Technology Ltd.",
  /* Bank4, 0x6e */ "MicroDisplay Corporation",
  /* Bank4, 0x6f */ "Team Group Inc.",
  /* Bank4, 0x70 */ "Sinett Corporation",
  /* Bank4, 0x71 */ "Toshiba Corporation",
  /* Bank4, 0x72 */ "Tensilica",
  /* Bank4, 0x73 */ "SiRF Technology",
  /* Bank4, 0x74 */ "Bacoc Inc.",
  /* Bank4, 0x75 */ "SMaL Camera Technologies",
  /* Bank4, 0x76 */ "Thomson SC",
  /* Bank4, 0x77 */ "Airgo Networks",
  /* Bank4, 0x78 */ "Wisair Ltd.",
  /* Bank4, 0x79 */ "SigmaTel",
  /* Bank4, 0x7a */ "Arkados",
  /* Bank4, 0x7b */ "Compete IT gmbH Co. KG",
  /* Bank4, 0x7c */ "Eudar Technology Inc.",
  /* Bank4, 0x7d */ "Focus Enhancements",
  /* Bank4, 0x7e */ "Xyratex",
  /* Bank5, 0x01 */ "Specular Networks",
  /* Bank5, 0x02 */ "Patriot Memory (PDP Systems)",
  /* Bank5, 0x03 */ "U-Chip Technology Corp.",
  /* Bank5, 0x04 */ "Silicon Optix",
  /* Bank5, 0x05 */ "Greenfield Networks",
  /* Bank5, 0x06 */ "CompuRAM GmbH",
  /* Bank5, 0x07 */ "Stargen, Inc.",
  /* Bank5, 0x08 */ "NetCell Corporation",
  /* Bank5, 0x09 */ "Excalibrus Technologies Ltd",
  /* Bank5, 0x0a */ "SCM Microsystems",
  /* Bank5, 0x0b */ "Xsigo Systems, Inc.",
  /* Bank5, 0x0c */ "CHIPS & Systems Inc",
  /* Bank5, 0x0d */ "Tier 1 Multichip Solutions",
  /* Bank5, 0x0e */ "CWRL Labs",
  /* Bank5, 0x0f */ "Teradici",
  /* Bank5, 0x10 */ "Gigaram, Inc.",
  /* Bank5, 0x11 */ "g2 Microsystems",
  /* Bank5, 0x12 */ "PowerFlash Semiconductor",
  /* Bank5, 0x13 */ "P.A. Semi, Inc.",
  /* Bank5, 0x14 */ "NovaTech Solutions, S.A.",
  /* Bank5, 0x15 */ "c2 Microsystems, Inc.",
  /* Bank5, 0x16 */ "Level5 Networks",
  /* Bank5, 0x17 */ "COS Memory AG",
  /* Bank5, 0x18 */ "Innovasic Semiconductor",
  /* Bank5, 0x19 */ "02IC Co. Ltd",
  /* Bank5, 0x1a */ "Tabula, Inc.",
  /* Bank5, 0x1b */ "Crucial Technology",
  /* Bank5, 0x1c */ "Chelsio Communications",
  /* Bank5, 0x1d */ "Solarflare Communications",
  /* Bank5, 0x1e */ "Xambala Inc.",
  /* Bank5, 0x1f */ "EADS Astrium",
  /* Bank5, 0x20 */ "Terra Semiconductor, Inc.",
  /* Bank5, 0x21 */ "Imaging Works, Inc.",
  /* Bank5, 0x22 */ "Astute Networks, Inc.",
  /* Bank5, 0x23 */ "Tzero",
  /* Bank5, 0x24 */ "Emulex",
  /* Bank5, 0x25 */ "Power-One",
  /* Bank5, 0x26 */ "Pulse~LINK Inc.",
  /* Bank5, 0x27 */ "Hon Hai Precision Industry",
  /* Bank5, 0x28 */ "White Rock Networks Inc.",
  /* Bank5, 0x29 */ "Telegent Systems USA, Inc.",
  /* Bank5, 0x2a */ "Atrua Technologies, Inc.",
  /* Bank5, 0x2b */ "Acbel Polytech Inc.",
  /* Bank5, 0x2c */ "eRide Inc.",
  /* Bank5, 0x2d */ "ULi Electronics Inc.",
  /* Bank5, 0x2e */ "Magnum Semiconductor Inc.",
  /* Bank5, 0x2f */ "neoOne Technology, Inc.",
  /* Bank5, 0x30 */ "Connex Technology, Inc.",
  /* Bank5, 0x31 */ "Stream Processors, Inc.",
  /* Bank5, 0x32 */ "Focus Enhancements",
  /* Bank5, 0x33 */ "Telecis Wireless, Inc.",
  /* Bank5, 0x34 */ "uNav Microelectronics",
  /* Bank5, 0x35 */ "Tarari, Inc.",
  /* Bank5, 0x36 */ "Ambric, Inc.",
  /* Bank5, 0x37 */ "Newport Media, Inc.",
  /* Bank5, 0x38 */ "VMTS",
  /* Bank5, 0x39 */ "Enuclia Semiconductor, Inc.",
  /* Bank5, 0x3a */ "Virtium Technology Inc.",
  /* Bank5, 0x3b */ "Solid State System Co., Ltd.",
  /* Bank5, 0x3c */ "Kian Tech LLC",
  /* Bank5, 0x3d */ "Artimi",
  /* Bank5, 0x3e */ "Power Quotient International",
  /* Bank5, 0x3f */ "Avago Technologies",
  /* Bank5, 0x40 */ "ADTechnology",
  /* Bank5, 0x41 */ "Sigma Designs",
  /* Bank5, 0x42 */ "SiCortex, Inc.",
  /* Bank5, 0x43 */ "Ventura Technology Group",
  /* Bank5, 0x44 */ "eASIC",
  /* Bank5, 0x45 */ "M.H.S. SAS",
  /* Bank5, 0x46 */ "Micro Star International",
  /* Bank5, 0x47 */ "Rapport Inc.",
  /* Bank5, 0x48 */ "Makway International",
  /* Bank5, 0x49 */ "Broad Reach Engineering Co.",
  /* Bank5, 0x4a */ "Semiconductor Mfg Intl Corp",
  /* Bank5, 0x4b */ "SiConnect",
  /* Bank5, 0x4c */ "FCI USA Inc.",
  /* Bank5, 0x4d */ "Validity Sensors",
  /* Bank5, 0x4e */ "Coney Technology Co. Ltd.",
  /* Bank5, 0x4f */ "Spans Logic",
  /* Bank5, 0x50 */ "Neterion Inc.",
  /* Bank5, 0x51 */ "Qimonda",
  /* Bank5, 0x52 */ "New Japan Radio Co. Ltd.",
  /* Bank5, 0x53 */ "Velogix",
  /* Bank5, 0x54 */ "Montalvo Systems",
  /* Bank5, 0x55 */ "iVivity Inc.",
  /* Bank5, 0x56 */ "Walton Chaintech",
  /* Bank5, 0x57 */ "AENEON",
  /* Bank5, 0x58 */ "Lorom Industrial Co. Ltd.",
  /* Bank5, 0x59 */ "Radiospire Networks",
  /* Bank5, 0x5a */ "Sensio Technologies, Inc.",
  /* Bank5, 0x5b */ "Nethra Imaging",
  /* Bank5, 0x5c */ "Hexon Technology Pte Ltd",
  /* Bank5, 0x5d */ "CompuStocx (CSX)",
  /* Bank5, 0x5e */ "Methode Electronics, Inc.",
  /* Bank5, 0x5f */ "Connect One Ltd.",
  /* Bank5, 0x60 */ "Opulan Technologies",
  /* Bank5, 0x61 */ "Septentrio NV",
  /* Bank5, 0x62 */ "Goldenmars Technology Inc.",
  /* Bank5, 0x63 */ "Kreton Corporation",
  /* Bank5, 0x64 */ "Cochlear Ltd.",
  /* Bank5, 0x65 */ "Altair Semiconductor",
  /* Bank5, 0x66 */ "NetEffect, Inc.",
  /* Bank5, 0x67 */ "Spansion, Inc.",
  /* Bank5, 0x68 */ "Taiwan Semiconductor Mfg",
  /* Bank5, 0x69 */ "Emphany Systems Inc.",
  /* Bank5, 0x6a */ "ApaceWave Technologies",
  /* Bank5, 0x6b */ "Mobilygen Corporation",
  /* Bank5, 0x6c */ "Tego",
  /* Bank5, 0x6d */ "Cswitch Corporation",
  /* Bank5, 0x6e */ "Haier (Beijing) IC Design Co.",
  /* Bank5, 0x6f */ "MetaRAM",
  /* Bank5, 0x70 */ "Axel Electronics Co. Ltd.",
  /* Bank5, 0x71 */ "Tilera Corporation",
  /* Bank5, 0x72 */ "Aquantia",
  /* Bank5, 0x73 */ "Vivace Semiconductor",
  /* Bank5, 0x74 */ "Redpine Signals",
  /* Bank5, 0x75 */ "Octalica",
  /* Bank5, 0x76 */ "InterDigital Communications",
  /* Bank5, 0x77 */ "Avant Technology",
  /* Bank5, 0x78 */ "Asrock, Inc.",
  /* Bank5, 0x79 */ "Availink",
  /* Bank5, 0x7a */ "Quartics, Inc.",
  /* Bank5, 0x7b */ "Element CXI",
  /* Bank5, 0x7c */ "Innovaciones Microelectronicas",
  /* Bank5, 0x7d */ "VeriSilicon Microelectronics",
  /* Bank5, 0x7e */ "W5 Networks",
  /* Bank6, 0x01 */ "MOVEKING",
  /* Bank6, 0x02 */ "Mavrix Technology, Inc.",
  /* Bank6, 0x03 */ "CellGuide Ltd.",
  /* Bank6, 0x04 */ "Faraday Technology",
  /* Bank6, 0x05 */ "Diablo Technologies, Inc.",
  /* Bank6, 0x06 */ "Jennic",
  /* Bank6, 0x07 */ "Octasic",
  /* Bank6, 0x08 */ "Molex Incorporated",
  /* Bank6, 0x09 */ "3Leaf Networks",
  /* Bank6, 0x0a */ "Bright Micron Technology",
  /* Bank6, 0x0b */ "Netxen",
  /* Bank6, 0x0c */ "NextWave Broadband Inc.",
  /* Bank6, 0x0d */ "DisplayLink",
  /* Bank6, 0x0e */ "ZMOS Technology",
  /* Bank6, 0x0f */ "Tec-Hill",
  /* Bank6, 0x10 */ "Multigig, Inc.",
  /* Bank6, 0x11 */ "Amimon",
  /* Bank6, 0x12 */ "Euphonic Technologies, Inc.",
  /* Bank6, 0x13 */ "BRN Phoenix",
  /* Bank6, 0x14 */ "InSilica",
  /* Bank6, 0x15 */ "Ember Corporation",
  /* Bank6, 0x16 */ "Avexir Technologies Corporation",
  /* Bank6, 0x17 */ "Echelon Corporation",
  /* Bank6, 0x18 */ "Edgewater Computer Systems",
  /* Bank6, 0x19 */ "XMOS Semiconductor Ltd.",
  /* Bank6, 0x1a */ "GENUSION, Inc.",
  /* Bank6, 0x1b */ "Memory Corp NV",
  /* Bank6, 0x1c */ "SiliconBlue Technologies",
  /* Bank6, 0x1d */ "Rambus Inc.",
  /* Bank6, 0x1e */ "Andes Technology Corporation",
  /* Bank6, 0x1f */ "Coronis Systems",
  /* Bank6, 0x20 */ "Achronix Semiconductor",
  /* Bank6, 0x21 */ "Siano Mobile Silicon Ltd.",
  /* Bank6, 0x22 */ "Semtech Corporation",
  /* Bank6, 0x23 */ "Pixelworks Inc.",
  /* Bank6, 0x24 */ "Gaisler Research AB",
  /* Bank6, 0x25 */ "Teranetics",
  /* Bank6, 0x26 */ "Toppan Printing Co. Ltd.",
  /* Bank6, 0x27 */ "Kingxcon",
  /* Bank6, 0x28 */ "Silicon Integrated Systems",
  /* Bank6, 0x29 */ "I-O Data Device, Inc.",
  /* Bank6, 0x2a */ "NDS Americas Inc.",
  /* Bank6, 0x2b */ "Solomon Systech Limited",
  /* Bank6, 0x2c */ "On Demand Microelectronics",
  /* Bank6, 0x2d */ "Amicus Wireless Inc.",
  /* Bank6, 0x2e */ "SMARDTV SNC",
  /* Bank6, 0x2f */ "Comsys Communication Ltd.",
  /* Bank6, 0x30 */ "Movidia Ltd.",
  /* Bank6, 0x31 */ "Javad GNSS, Inc.",
  /* Bank6, 0x32 */ "Montage Technology Group",
  /* Bank6, 0x33 */ "Trident Microsystems",
  /* Bank6, 0x34 */ "Super Talent",
  /* Bank6, 0x35 */ "Optichron, Inc.",
  /* Bank6, 0x36 */ "Future Waves UK Ltd.",
  /* Bank6, 0x37 */ "SiBEAM, Inc.",
  /* Bank6, 0x38 */ "Inicore,Inc.",
  /* Bank6, 0x39 */ "Virident Systems",
  /* Bank6, 0x3a */ "M2000, Inc.",
  /* Bank6, 0x3b */ "ZeroG Wireless, Inc.",
  /* Bank6, 0x3c */ "Gingle Technology Co. Ltd.",
  /* Bank6, 0x3d */ "Space Micro Inc.",
  /* Bank6, 0x3e */ "Wilocity",
  /* Bank6, 0x3f */ "Novafora, Inc.",
  /* Bank6, 0x40 */ "iKoa Corporation",
  /* Bank6, 0x41 */ "ASint Technology",
  /* Bank6, 0x42 */ "Ramtron",
  /* Bank6, 0x43 */ "Plato Networks Inc.",
  /* Bank6, 0x44 */ "IPtronics AS",
  /* Bank6, 0x45 */ "Infinite-Memories",
  /* Bank6, 0x46 */ "Parade Technologies Inc.",
  /* Bank6, 0x47 */ "Dune Networks",
  /* Bank6, 0x48 */ "GigaDevice Semiconductor",
  /* Bank6, 0x49 */ "Modu Ltd.",
  /* Bank6, 0x4a */ "CEITEC",
  /* Bank6, 0x4b */ "Northrop Grumman",
  /* Bank6, 0x4c */ "XRONET Corporation",
  /* Bank6, 0x4d */ "Sicon Semiconductor AB",
  /* Bank6, 0x4e */ "Atla Electronics Co. Ltd.",
  /* Bank6, 0x4f */ "TOPRAM Technology",
  /* Bank6, 0x50 */ "Silego Technology Inc.",
  /* Bank6, 0x51 */ "Kinglife",
  /* Bank6, 0x52 */ "Ability Industries Ltd.",
  /* Bank6, 0x53 */ "Silicon Power Computer &",
  /* Bank6, 0x54 */ "Augusta Technology, Inc.",
  /* Bank6, 0x55 */ "Nantronics Semiconductors",
  /* Bank6, 0x56 */ "Hilscher Gesellschaft",
  /* Bank6, 0x57 */ "Quixant Ltd.",
  /* Bank6, 0x58 */ "Percello Ltd.",
  /* Bank6, 0x59 */ "NextIO Inc.",
  /* Bank6, 0x5a */ "Scanimetrics Inc.",
  /* Bank6, 0x5b */ "FS-Semi Company Ltd.",
  /* Bank6, 0x5c */ "Infinera Corporation",
  /* Bank6, 0x5d */ "SandForce Inc.",
  /* Bank6, 0x5e */ "Lexar Media",
  /* Bank6, 0x5f */ "Teradyne Inc.",
  /* Bank6, 0x60 */ "Memory Exchange Corp.",
  /* Bank6, 0x61 */ "Suzhou Smartek Electronics",
  /* Bank6, 0x62 */ "Avantium Corporation",
  /* Bank6, 0x63 */ "ATP Electronics Inc.",
  /* Bank6, 0x64 */ "Valens Semiconductor Ltd",
  /* Bank6, 0x65 */ "Agate Logic, Inc.",
  /* Bank6, 0x66 */ "Netronome",
  /* Bank6, 0x67 */ "Zenverge, Inc.",
  /* Bank6, 0x68 */ "N-trig Ltd",
  /* Bank6, 0x69 */ "SanMax Technologies Inc.",
  /* Bank6, 0x6a */ "Contour Semiconductor Inc.",
  /* Bank6, 0x6b */ "TwinMOS",
  /* Bank6, 0x6c */ "Silicon Systems, Inc.",
  /* Bank6, 0x6d */ "V-Color Technology Inc.",
  /* Bank6, 0x6e */ "Certicom Corporation",
  /* Bank6, 0x6f */ "JSC ICC Milandr",
  /* Bank6, 0x70 */ "PhotoFast Global Inc.",
  /* Bank6, 0x71 */ "InnoDisk Corporation",
  /* Bank6, 0x72 */ "Muscle Power",
  /* Bank6, 0x73 */ "Energy Micro",
  /* Bank6, 0x74 */ "Innofidei",
  /* Bank6, 0x75 */ "CopperGate Communications",
  /* Bank6, 0x76 */ "Holtek Semiconductor Inc.",
  /* Bank6, 0x77 */ "Myson Century, Inc.",
  /* Bank6, 0x78 */ "FIDELIX",
  /* Bank6, 0x79 */ "Red Digital Cinema",
  /* Bank6, 0x7a */ "Densbits Technology",
  /* Bank6, 0x7b */ "Zempro",
  /* Bank6, 0x7c */ "MoSys",
  /* Bank6, 0x7d */ "Provigent",
  /* Bank6, 0x7e */ "Triad Semiconductor, Inc.",
  /* Bank7, 0x01 */ "Siklu Communication Ltd.",
  /* Bank7, 0x02 */ "A Force Manufacturing Ltd.",
  /* Bank7, 0x03 */ "Strontium",
  /* Bank7, 0x04 */ "ALi Corp (Abilis Systems)",
  /* Bank7, 0x05 */ "Siglead, Inc.",
  /* Bank7, 0x06 */ "Ubicom, Inc.",
  /* Bank7, 0x07 */ "Unifosa Corporation",
  /* Bank7, 0x08 */ "Stretch, Inc.",
  /* Bank7, 0x09 */ "Lantiq Deutschland GmbH",
  /* Bank7, 0x0a */ "Visipro.",
  /* Bank7, 0x0b */ "EKMemory",
  /* Bank7, 0x0c */ "Microelectronics Institute ZTE",
  /* Bank7, 0x0d */ "u-blox AG",
  /* Bank7, 0x0e */ "Carry Technology Co. Ltd.",
  /* Bank7, 0x0f */ "Nokia",
  /* Bank7, 0x10 */ "King Tiger Technology",
  /* Bank7, 0x11 */ "Sierra Wireless",
  /* Bank7, 0x12 */ "HT Micron",
  /* Bank7, 0x13 */ "Albatron Technology Co. Ltd.",
  /* Bank7, 0x14 */ "Leica Geosystems AG",
  /* Bank7, 0x15 */ "BroadLight",
  /* Bank7, 0x16 */ "AEXEA",
  /* Bank7, 0x17 */ "ClariPhy Communications, Inc.",
  /* Bank7, 0x18 */ "Green Plug",
  /* Bank7, 0x19 */ "Design Art Networks",
  /* Bank7, 0x1a */ "Mach Xtreme Technology Ltd.",
  /* Bank7, 0x1b */ "ATO Solutions Co. Ltd.",
  /* Bank7, 0x1c */ "Ramsta",
  /* Bank7, 0x1d */ "Greenliant Systems, Ltd.",
  /* Bank7, 0x1e */ "Teikon",
  /* Bank7, 0x1f */ "Antec Hadron",
  /* Bank7, 0x20 */ "NavCom Technology, Inc.",
  /* Bank7, 0x21 */ "Shanghai Fudan Microelectronics",
  /* Bank7, 0x22 */ "Calxeda, Inc.",
  /* Bank7, 0x23 */ "JSC EDC Electronics",
  /* Bank7, 0x24 */ "Kandit Technology Co. Ltd.",
  /* Bank7, 0x25 */ "Ramos Technology",
  /* Bank7, 0x26 */ "Goldenmars Technology",
  /* Bank7, 0x27 */ "XeL Technology Inc.",
  /* Bank7, 0x28 */ "Newzone Corporation",
  /* Bank7, 0x29 */ "ShenZhen MercyPower Tech",
  /* Bank7, 0x2a */ "Nanjing Yihuo Technology",
  /* Bank7, 0x2b */ "Nethra Imaging Inc.",
  /* Bank7, 0x2c */ "SiTel Semiconductor BV",
  /* Bank7, 0x2d */ "SolidGear Corporation",
  /* Bank7, 0x2e */ "Topower Computer Ind Co Ltd.",
  /* Bank7, 0x2f */ "Wilocity",
  /* Bank7, 0x30 */ "Profichip GmbH",
  /* Bank7, 0x31 */ "Gerad Technologies",
  /* Bank7, 0x32 */ "Ritek Corporation",
  /* Bank7, 0x33 */ "Gomos Technology Limited",
  /* Bank7, 0x34 */ "Memoright Corporation",
  /* Bank7, 0x35 */ "D-Broad, Inc.",
  /* Bank7, 0x36 */ "HiSilicon Technologies",
  /* Bank7, 0x37 */ "Syndiant Inc..",
  /* Bank7, 0x38 */ "Enverv Inc.",
  /* Bank7, 0x39 */ "Cognex",
  /* Bank7, 0x3a */ "Xinnova Technology Inc.",
  /* Bank7, 0x3b */ "Ultron AG",
  /* Bank7, 0x3c */ "Concord Idea Corporation",
  /* Bank7, 0x3d */ "AIM Corporation",
  /* Bank7, 0x3e */ "Lifetime Memory Products",
  /* Bank7, 0x3f */ "Ramsway",
  /* Bank7, 0x40 */ "Recore Systems B.V.",
  /* Bank7, 0x41 */ "Haotian Jinshibo Science Tech",
  /* Bank7, 0x42 */ "Being Advanced Memory",
  /* Bank7, 0x43 */ "Adesto Technologies",
  /* Bank7, 0x44 */ "Giantec Semiconductor, Inc.",
  /* Bank7, 0x45 */ "HMD Electronics AG",
  /* Bank7, 0x46 */ "Gloway International (HK)",
  /* Bank7, 0x47 */ "Kingcore",
  /* Bank7, 0x48 */ "Anucell Technology Holding",
  /* Bank7, 0x49 */ "Accord Software & Systems Pvt. Ltd.",
  /* Bank7, 0x4a */ "Active-Semi Inc.",
  /* Bank7, 0x4b */ "Denso Corporation",
  /* Bank7, 0x4c */ "TLSI Inc.",
  /* Bank7, 0x4d */ "Qidan",
  /* Bank7, 0x4e */ "Mustang",
  /* Bank7, 0x4f */ "Orca Systems",
  /* Bank7, 0x50 */ "Passif Semiconductor",
  /* Bank7, 0x51 */ "GigaDevice Semiconductor (Beijing)",
  /* Bank7, 0x52 */ "Memphis Electronic",
  /* Bank7, 0x53 */ "Beckhoff Automation GmbH",
  /* Bank7, 0x54 */ "Harmony Semiconductor Corp",
  /* Bank7, 0x55 */ "Air Computers SRL",
  /* Bank7, 0x56 */ "TMT Memory",
  /* Bank7, 0x57 */ "Eorex Corporation",
  /* Bank7, 0x58 */ "Xingtera",
  /* Bank7, 0x59 */ "Netsol",
  /* Bank7, 0x5a */ "Bestdon Technology Co. Ltd.",
  /* Bank7, 0x5b */ "Baysand Inc.",
  /* Bank7, 0x5c */ "Uroad Technology Co. Ltd.",
  /* Bank7, 0x5d */ "Wilk Elektronik S.A.",
  /* Bank7, 0x5e */ "AAI",
  /* Bank7, 0x5f */ "Harman",
  /* Bank7, 0x60 */ "Berg Microelectronics Inc.",
  /* Bank7, 0x61 */ "ASSIA, Inc.",
  /* Bank7, 0x62 */ "Visiontek Products LLC",
  /* Bank7, 0x63 */ "OCMEMORY",
  /* Bank7, 0x64 */ "Welink Solution Inc.",
  /* Bank7, 0x65 */ "Shark Gaming",
  /* Bank7, 0x66 */ "Avalanche Technology",
  /* Bank7, 0x67 */ "R&D Center ELVEES OJSC",
  /* Bank7, 0x68 */ "KingboMars Technology Co. Ltd.",
  /* Bank7, 0x69 */ "High Bridge Solutions Industria",
  /* Bank7, 0x6a */ "Transcend Technology Co. Ltd.",
  /* Bank7, 0x6b */ "Everspin Technologies",
  /* Bank7, 0x6c */ "Hon-Hai Precision",
  /* Bank7, 0x6d */ "Smart Storage Systems",
  /* Bank7, 0x6e */ "Toumaz Group",
  /* Bank7, 0x6f */ "Zentel Electronics Corporation",
  /* Bank7, 0x70 */ "Panram International Corporation",
  /* Bank7, 0x71 */ "Silicon Space Technology",
  /* Bank7, 0x72 */ "LITE-ON IT Corporation",
  /* Bank7, 0x73 */ "Inuitive",
  /* Bank7, 0x74 */ "HMicro",
  /* Bank7, 0x75 */ "BittWare, Inc.",
  /* Bank7, 0x76 */ "GLOBALFOUNDRIES",
  /* Bank7, 0x77 */ "ACPI Digital Co. Ltd.",
  /* Bank7, 0x78 */ "Annapurna Labs",
  /* Bank7, 0x79 */ "AcSiP Technology Corporation",
  /* Bank7, 0x7a */ "Idea! Electronic Systems",
  /* Bank7, 0x7b */ "Gowe Technology Co. Ltd.",
  /* Bank7, 0x7c */ "Hermes Testing Solutions, Inc.",
  /* Bank7, 0x7d */ "Positivo BGH",
  /* Bank7, 0x7e */ "Intelligence Silicon Technology",
  /* Bank8, 0x01 */ "3D PLUS",
  /* Bank8, 0x02 */ "Diehl Aerospace",
  /* Bank8, 0x03 */ "Fairchild",
  /* Bank8, 0x04 */ "Mercury Systems",
  /* Bank8, 0x05 */ "Sonics, Inc.",
  /* Bank8, 0x06 */ "GE Intelligent Platforms GmbH & Co.",
  /* Bank8, 0x07 */ "Shenzhen Jinge Information Co. Ltd.",
  /* Bank8, 0x08 */ "SCWW",
  /* Bank8, 0x09 */ "Silicon Motion Inc.",
  /* Bank8, 0x0a */ "Anurag",
  /* Bank8, 0x0b */ "King Kong",
  /* Bank8, 0x0c */ "FROM30 Co. Ltd.",
  /* Bank8, 0x0d */ "Gowin Semiconductor Corp",
  /* Bank8, 0x0e */ "Fremont Micro Devices Ltd.",
  /* Bank8, 0x0f */ "Ericsson Modems",
  /* Bank8, 0x10 */ "Exelis",
  /* Bank8, 0x11 */ "Satixfy Ltd.",
  /* Bank8, 0x12 */ "Galaxy Microsystems Ltd.",
  /* Bank8, 0x13 */ "Gloway International Co. Ltd.",
  /* Bank8, 0x14 */ "Lab",
  /* Bank8, 0x15 */ "Smart Energy Instruments",
  /* Bank8, 0x16 */ "Approved Memory Corporation",
  /* Bank8, 0x17 */ "Axell Corporation",
  /* Bank8, 0x18 */ "Essencore Limited",
  /* Bank8, 0x19 */ "Phytium",
  /* Bank8, 0x1a */ "Xian SinoChip Semiconductor",
  /* Bank8, 0x1b */ "Ambiq Micro",
  /* Bank8, 0x1c */ "eveRAM Technology, Inc.",
  /* Bank8, 0x1d */ "Infomax",
  /* Bank8, 0x1e */ "Butterfly Network, Inc.",
  /* Bank8, 0x1f */ "Shenzhen City Gcai Electronics",
  /* Bank8, 0x20 */ "Stack Devices Corporation",
  /* Bank8, 0x21 */ "ADK Media Group",
  /* Bank8, 0x22 */ "TSP Global Co., Ltd.",
  /* Bank8, 0x23 */ "HighX",
  /* Bank8, 0x24 */ "Shenzhen Elicks Technology",
  /* Bank8, 0x25 */ "ISSI/Chingis",
  /* Bank8, 0x26 */ "Google, Inc.",
  /* Bank8, 0x27 */ "Dasima International Development",
  /* Bank8, 0x28 */ "Leahkinn Technology Limited",
  /* Bank8, 0x29 */ "HIMA Paul Hildebrandt GmbH Co KG",
  /* Bank8, 0x2a */ "Keysight Technologies",
  /* Bank8, 0x2b */ "Techcomp International (Fastable)",
  /* Bank8, 0x2c */ "Ancore Technology Corporation",
  /* Bank8, 0x2d */ "Nuvoton",
  /* Bank8, 0x2e */ "Korea Uhbele International Group Ltd.",
  /* Bank8, 0x2f */ "Ikegami Tsushinki Co Ltd.",
  /* Bank8, 0x30 */ "RelChip, Inc.",
  /* Bank8, 0x31 */ "Baikal Electronics",
  /* Bank8, 0x32 */ "Nemostech Inc.",
  /* Bank8, 0x33 */ "Memorysolution GmbH",
  /* Bank8, 0x34 */ "Silicon Integrated Systems Corporation",
  /* Bank8, 0x35 */ "Xiede",
  /* Bank8, 0x36 */ "Multilaser Components",
  /* Bank8, 0x37 */ "Flash Chi",
  /* Bank8, 0x38 */ "Jone",
  /* Bank8, 0x39 */ "GCT Semiconductor Inc.",
  /* Bank8, 0x3a */ "Hong Kong Zetta Device Technology",
  /* Bank8, 0x3b */ "Unimemory Technology(s) Pte Ltd.",
  /* Bank8, 0x3c */ "Cuso",
  /* Bank8, 0x3d */ "Kuso",
  /* Bank8, 0x3e */ "Uniquify Inc.",
  /* Bank8, 0x3f */ "Skymedi Corporation",
  /* Bank8, 0x40 */ "Core Chance Co. Ltd.",
  /* Bank8, 0x41 */ "Tekism Co. Ltd.",
  /* Bank8, 0x42 */ "Seagate Technology PLC",
  /* Bank8, 0x43 */ "Hong Kong Gaia Group Co. Limited",
  /* Bank8, 0x44 */ "Gigacom Semiconductor LLC",
  /* Bank8, 0x45 */ "V2 Technologies",
  /* Bank8, 0x46 */ "TLi",
  /* Bank8, 0x47 */ "Neotion",
  /* Bank8, 0x48 */ "Lenovo",
  /* Bank8, 0x49 */ "Shenzhen Zhongteng Electronic Corp. Ltd.",
  /* Bank8, 0x4a */ "Compound Photonics",
  /* Bank8, 0x4b */ "in2H2 inc",
  /* Bank8, 0x4c */ "Shenzhen Pango Microsystems Co. Ltd",
  /* Bank8, 0x4d */ "Vasekey",
  /* Bank8, 0x4e */ "Cal-Comp Industria de Semicondutores",
  /* Bank8, 0x4f */ "Eyenix Co., Ltd.",
  /* Bank8, 0x50 */ "Heoriady",
  /* Bank8, 0x51 */ "Accelerated Memory Production Inc.",
  /* Bank8, 0x52 */ "INVECAS, Inc.",
  /* Bank8, 0x53 */ "AP Memory",
  /* Bank8, 0x54 */ "Douqi Technology",
  /* Bank8, 0x55 */ "Etron Technology, Inc.",
  /* Bank8, 0x56 */ "Indie Semiconductor",
  /* Bank8, 0x57 */ "Socionext Inc.",
  /* Bank8, 0x58 */ "HGST",
  /* Bank8, 0x59 */ "EVGA",
  /* Bank8, 0x5a */ "Audience Inc.",
  /* Bank8, 0x5b */ "EpicGear",
  /* Bank8, 0x5c */ "Vitesse Enterprise Co.",
  /* Bank8, 0x5d */ "Foxtronn International Corporation",
  /* Bank8, 0x5e */ "Bretelon Inc.",
  /* Bank8, 0x5f */ "Graphcore",
  /* Bank8, 0x60 */ "Eoplex Inc",
  /* Bank8, 0x61 */ "MaxLinear, Inc.",
  /* Bank8, 0x62 */ "ETA Devices",
  /* Bank8, 0x63 */ "LOKI",
  /* Bank8, 0x64 */ "IMS Electronics Co., Ltd.",
  /* Bank8, 0x65 */ "Dosilicon Co., Ltd.",
  /* Bank8, 0x66 */ "Dolphin Integration",
  /* Bank8, 0x67 */ "Shenzhen Mic Electronics Technology",
  /* Bank8, 0x68 */ "Boya Microelectronics Inc.",
  /* Bank8, 0x69 */ "Geniachip (Roche)",
  /* Bank8, 0x6a */ "Axign",
  /* Bank8, 0x6b */ "Kingred Electronic Technology Ltd.",
  /* Bank8, 0x6c */ "Chao Yue Zhuo Computer Business Dept.",
  /* Bank8, 0x6d */ "Guangzhou Si Nuo Electronic Technology.",
  /* Bank8, 0x6e */ "Crocus Technology Inc.",
  /* Bank8, 0x6f */ "Creative Chips GmbH",
  /* Bank8, 0x70 */ "GE Aviation Systems LLC.",
  /* Bank8, 0x71 */ "Asgard",
  /* Bank8, 0x72 */ "Good Wealth Technology Ltd.",
  /* Bank8, 0x73 */ "TriCor Technologies",
  /* Bank8, 0x74 */ "Nova-Systems GmbH",
  /* Bank8, 0x75 */ "JUHOR",
  /* Bank8, 0x76 */ "Zhuhai Douke Commerce Co. Ltd.",
  /* Bank8, 0x77 */ "DSL Memory",
  /* Bank8, 0x78 */ "Anvo-Systems Dresden GmbH",
  /* Bank8, 0x79 */ "Realtek",
  /* Bank8, 0x7a */ "AltoBeam",
  /* Bank8, 0x7b */ "Wave Computing",
  /* Bank8, 0x7c */ "Beijing TrustNet Technology Co. Ltd.",
  /* Bank8, 0x7d */ "Innovium, Inc.",
  /* Bank8, 0x7e */ "Starsway Technology Limited",
  /* Bank9, 0x01 */ "Weltronics Co. LTD",
  /* Bank9, 0x02 */ "VMware, Inc.",
  /* Bank9, 0x03 */ "Hewlett Packard Enterprise",
  /* Bank9, 0x04 */ "INTENSO",
  /* Bank9, 0x05 */ "Puya Semiconductor",
  /* Bank9, 0x06 */ "MEMORFI",
  /* Bank9, 0x07 */ "MSC Technologies GmbH",
  /* Bank9, 0x08 */ "Txrui",
  /* Bank9, 0x09 */ "SiFive, Inc.",
  /* Bank9, 0x0a */ "Spreadtrum Communications",
  /* Bank9, 0x0b */ "Paragon Technology (Shenzhen) Ltd.",
  /* Bank9, 0x0c */ "UMAX Technology",
  /* Bank9, 0x0d */ "Shenzhen Yong Sheng Technology",
  /* Bank9, 0x0e */ "SNOAMOO (Shenzhen Kai Zhuo Yue)",
  /* Bank9, 0x0f */ "Daten Tecnologia LTDA",
  /* Bank9, 0x10 */ "Shenzhen XinRuiYan Electronics",
  /* Bank9, 0x11 */ "Eta Compute",
  /* Bank9, 0x12 */ "Energous",
  /* Bank9, 0x13 */ "Raspberry Pi Trading Ltd.",
  /* Bank9, 0x14 */ "Shenzhen Chixingzhe Tech Co. Ltd.",
  /* Bank9, 0x15 */ "Silicon Mobility",
  /* Bank9, 0x16 */ "IQ-Analog Corporation",
  /* Bank9, 0x17 */ "Uhnder, Inc.",
  /* Bank9, 0x18 */ "Impinj",
  /* Bank9, 0x19 */ "DEPO Computers",
  /* Bank9, 0x1a */ "Nespeed Sysems",
  /* Bank9, 0x1b */ "Yangtze Memory Technologies Co. Ltd",
  /* Bank9, 0x1c */ "MemxPro Inc.",
  /* Bank9, 0x1d */ "Tammuz Co., Ltd.",
  /* Bank9, 0x1e */ "Allwinner Technology",
  /* Bank9, 0x1f */ "Qing Xuan Tong Computer Trading Firm",
  /* Bank9, 0x20 */ "XMC",
  /* Bank9, 0x21 */ "Teclast",
  /* Bank9, 0x22 */ "Maxsun",
  /* Bank9, 0x23 */ "Haiguang Integrated Circuit Design",
  /* Bank9, 0x24 */ "RamCENTER Technology",
  /* Bank9, 0x25 */ "Phison Electronics Corporation",
  /* Bank9, 0x26 */ "Guizhou Huaxintong Semi-Conductor",
  /* Bank9, 0x27 */ "Network Intelligence",
  /* Bank9, 0x28 */ "Continental Technology (Holdings)",
  /* Bank9, 0x29 */ "Guangzhou Huayan Suning Electronic",
  /* Bank9, 0x2a */ "Guangzhou Zhouji Electronic Co., Ltd.",
  /* Bank9, 0x2b */ "Shenzhen Giant Hui Kang Tech Co. Ltd",
  /* Bank9, 0x2c */ "Shenzhen Yilong Innovative Co. Ltd.",
  /* Bank9, 0x2d */ "Neo Forza",
  /* Bank9, 0x2e */ "Lyontek Inc.",
  /* Bank9, 0x2f */ "Shanghai Kuxin Microelectronics Ltd.",
  /* Bank9, 0x30 */ "Shenzhen Larix Technology Co. Ltd.",
  /* Bank9, 0x31 */ "Qbit Semiconductor Ltd.",
  /* Bank9, 0x32 */ "Insignis Technology Corporation",
  /* Bank9, 0x33 */ "Lanson Memory Co. Ltd.",
  /* Bank9, 0x34 */ "Shenzhen Superway Electronics Co Ltd",
  /* Bank9, 0x35 */ "Canaan-Creative Co. Ltd.",
  /* Bank9, 0x36 */ "Black Diamond Memory",
  /* Bank9, 0x37 */ "Shenzhen City Parker Baking Electronics",
  /* Bank9, 0x38 */ "Shenzhen Baihong Technology Co. Ltd.",
  /* Bank9, 0x39 */ "GEO Semiconductors",
  /* Bank9, 0x3a */ "DTG NEO Scientific Ltd.",
  /* Bank9, 0x3b */ "Artery Technology Co. Ltd.",
  /* Bank9, 0x3c */ "Jinyu",
  /* Bank9, 0x3d */ "ShenzhenYing Chi Technology Development",
  /* Bank9, 0x3e */ "Shenzhen Pengcheng Xin Technology",
  /* Bank9, 0x3f */ "Pegasus Semiconductor (Shanghai) Co.",
  /* Bank9, 0x40 */ "Mythic, Inc.",
  /* Bank9, 0x41 */ "Elmos Semiconductor AG",
  /* Bank9, 0x42 */ "Kllisre",
  /* Bank9, 0x43 */ "Shenzhen Yuan Chuang Wei Tech",
  /* Bank9, 0x44 */ "Shenzhen Xingmem Technology Corp."
  /* EOF */
};

/**
  Returns the manufacturer string.

  @param  Bank    The bank number, start from 0, such as Bank 0, Bank 1, ...
  @param  Id      The manufacturer id number, start from 1, max is 126.

  @return         The manufacturer string, in CHAR8 form.

**/
CHAR8 * Jep106GetManufacturerString(
  UINT8  Bank,
  UINT8  Id
)
{
	UINTN  Index;

  if (Id < 1 || Id > JEP106_BANK_MAX_ITEM_NUM) {
    DEBUG((EFI_D_ERROR, "Error: Manufacturer Id out of range[1, 126]!\n"));
    return "<Invalid>";
  }

  Index = (Bank * JEP106_BANK_MAX_ITEM_NUM) + Id - 1;
  if (Bank > JEP106_MAX_BANK_NUM || Jep106[Index] == 0) {
  	DEBUG((EFI_D_ERROR, "Error: Manufacturer Id is not in the list.\n"));
    return "<Unknown>";
  }

  return Jep106[Index];
}

