//**********************************************************************
//**********************************************************************
//**                                                                  **
//**     Copyright (c) 2015 Shanghai Zhaoxin Semiconductor Co., Ltd.  **
//**                                                                  **
//**********************************************************************
//**********************************************************************

#include <Uefi.h>
#include <Library/IoLib.h>
#include <Library/DebugLib.h>
#include <PlatformDefinition.h>


// SATA IDE Device ID and LPC Device ID are used to patch linux installation
// DO NOT MODIFY IT.
VOID UpdateSsid(VOID)
{
  MmioWrite32(HC_PCI_REG(PCI_SSID_REG),  MmioRead32(HC_PCI_REG(PCI_VID_REG)));
  MmioWrite32(ERRRPT_PCI_REG(PCI_SSID_REG), MmioRead32(ERRRPT_PCI_REG(PCI_VID_REG)));
  MmioWrite32(HIF_PCI_REG(PCI_SSID_REG),  MmioRead32(HIF_PCI_REG(PCI_VID_REG)));   
  MmioWrite32(DRAM_PCI_REG(PCI_SSID_REG),  MmioRead32(DRAM_PCI_REG(PCI_VID_REG)));
  MmioWrite32(NPMC_PCI_REG(PCI_SSID_REG),  MmioRead32(NPMC_PCI_REG(PCI_VID_REG)));
  MmioWrite32(APIC_PCI_REG(PCI_SSID_REG),  MmioRead32(APIC_PCI_REG(PCI_VID_REG)));
  MmioWrite32(SCRCH_PCI_REG(PCI_SSID_REG), MmioRead32(SCRCH_PCI_REG(PCI_VID_REG)));
  MmioWrite32(RAIDA1_PCI_REG(PCI_SSID_REG), MmioRead32(RAIDA1_PCI_REG(PCI_VID_REG)));

//HYL-20160916-start
//PCI UART
  MmioOr8(UART0_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SVIDEN);
  MmioOr8(UART0_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SSIDEN);
  MmioWrite32(UART0_PCI_REG(PCI_SSID_REG), MmioRead32(UART0_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART0_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SVIDEN);
  MmioAnd8(UART0_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SSIDEN);
  MmioOr8(UART1_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SVIDEN);
  MmioOr8(UART1_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SSIDEN);
  MmioWrite32(UART1_PCI_REG(PCI_SSID_REG), MmioRead32(UART1_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART1_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SVIDEN);
  MmioAnd8(UART1_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SSIDEN);
  #if 0
  MmioOr8(UART2_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SVIDEN);
  MmioOr8(UART2_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SSIDEN);
  MmioWrite32(UART2_PCI_REG(PCI_SSID_REG), MmioRead32(UART2_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART2_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SVIDEN);
  MmioAnd8(UART2_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SSIDEN);
  MmioOr8(UART3_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SVIDEN);
  MmioOr8(UART3_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), D10F0F1_SSIDEN);
  MmioWrite32(UART3_PCI_REG(PCI_SSID_REG), MmioRead32(UART3_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART3_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SVIDEN);
  MmioAnd8(UART3_PCI_REG(D10F0F1_BACK_DOOR_CTL_REG), (UINT8)~D10F0F1_SSIDEN);  
  #endif
//eSPI
  MmioOr8(ESPI_PCI_REG(D11F0_BACK_DOOR_ENABLE), D11F0_EN2CW);
  MmioWrite32(ESPI_PCI_REG(PCI_SSID_REG), MmioRead32(ESPI_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(ESPI_PCI_REG(D11F0_BACK_DOOR_ENABLE), (UINT8)~D11F0_EN2CW);
//LPC
  MmioWrite32(LPC_PCI_REG(D17F0_SVID_BACKDOOR_REGS), MmioRead32(LPC_PCI_REG(PCI_VID_REG)));
//HYL-20160916-end    

  MmioWrite32(SNMIC_PCI_REG(SNMIC_SSID_BACKDOOR_REG), MmioRead32(SNMIC_PCI_REG(PCI_VID_REG)));
  MmioOr8(SNMIC_PCI_REG(SNMIC_PCI_IO_CYCLE_CTRL_REG), SNMIC_RX2C_SEL);

// UHCI 0 ~ 2
  //MmioOr8(UHCI_PCI_REG(0, USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(UHCI_PCI_REG(0, PCI_SSID_REG),  MmioRead32(UHCI_PCI_REG(0, PCI_VID_REG)));
  //MmioAnd8(UHCI_PCI_REG(0, USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

  //MmioOr8(UHCI_PCI_REG(1, USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(UHCI_PCI_REG(1, PCI_SSID_REG),  MmioRead32(UHCI_PCI_REG(1, PCI_VID_REG)));
  //MmioAnd8(UHCI_PCI_REG(1, USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

  //MmioOr8(UHCI_PCI_REG(2, USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(UHCI_PCI_REG(2, PCI_SSID_REG),  MmioRead32(UHCI_PCI_REG(2, PCI_VID_REG)));
  //MmioAnd8(UHCI_PCI_REG(2, USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

// EHCI
  //MmioOr8(EHCI_PCI_REG(USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(EHCI_PCI_REG(PCI_SSID_REG),  MmioRead32(EHCI_PCI_REG(PCI_VID_REG)));
  //MmioAnd8(EHCI_PCI_REG(USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

// HDAC
  MmioOr8(HDAC_PCI_REG(HDAC_SSID_BACKDOOR_EN_REG), HDAC_SSID_BACKDOOR_EN);
  MmioWrite32(HDAC_PCI_REG(PCI_SSID_REG), MmioRead32(HDAC_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(HDAC_PCI_REG(HDAC_SSID_BACKDOOR_EN_REG), (UINT8)~HDAC_SSID_BACKDOOR_EN);  

}
